### ISSUE TITLE
Minimum ABI warning

### ISSUE THREAD

**Issue by wsfulton** [trailofbits/abi3audit#101]
When running:
```shell
abi3audit --assume-minimum-abi3 3.4 --report -o example_abi3_report.json _example.abi3.so
```
I see:
```shell
[07:32:43] WARNING  no wheel to infer abi3 version from; assuming (3.4)                                                                                                                      _object.py:53
[07:32:44] 💁 _example.abi3.so: 1 extensions scanned; 0 ABI version mismatches and 0 ABI violations found                                                                                                 
```
It seems that this warning is pointless as I tell abi3audit to use a .so instead of a wheel and I tell it the minimum version to assume. Is either of these possible:

1. Can the warning be removed when using `--assume-minimum-abi3` ?
2. Add in a warning control system for named/numbered warnings in the same way that compiler warnings can be individually turned on and off, like the `-W` family of options in gcc?

**Comment by woodruffw** [comment]
IMO it'd be useful to keep around as a `DEBUG` and not a `WARNING` (since it helps me root-cause user reports), but I agree that it's pointless as a warning when the user explicitly sets `--assume-minimum-abi3`.

Would you be interested in sending a PR for that? Otherwise I'll likely get to it today or tomorrow.

**Comment by wsfulton** [comment]
I might just leave this to you if you don't mind as I don't quite understand if you'd prefer a warning instead of debug when --assume-minimum-abi3 is actually set.

**Comment by woodruffw** [comment]
> if you'd prefer a warning instead of debug when --assume-minimum-abi3 is actually set.

Yeah, I was thinking an unconditional `DEBUG` (since it's still useful information to have when debugging). But I'll do this one.

**Comment by woodruffw** [comment]
Done with #103. Let me know if you'd like a release for this, otherwise I'm likely to do it when the next round of feature changes happens!

**Comment by wsfulton** [comment]
Thanks. No rush for you to make a release from my side.
