### ISSUE TITLE
Trusted Publishing — split the jobs?

### ISSUE THREAD

**Issue by webknjaz** [trailofbits/abi3audit#104]
@woodruffw I was surprised to see that https://github.com/trailofbits/abi3audit/blob/main/.github/workflows/release.yml doesn't follow the recommendations from https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ and gives `id-token: write` to the build backend invocation. Was this overlooked?

**Comment by woodruffw** [comment]
> Was this overlooked?

Sort of -- I think I probably made that workflow before the current PyPA recommended one was updated to include Trusted Publishing. 

Looks like I added it last March: https://github.com/trailofbits/abi3audit/commit/cf979bba12bd027c796d4a9b766b326b9cdec58a

...and the PyPA docs began to be updated last August-ish: https://github.com/pypa/packaging.python.org/commit/b869257a3b4011f4c26df89a8758305f03764c7f

I don't mind updating it to use the separate step pattern, but I also think the packaging guidance may need to become more nuanced over time: `id-token: write` may eventually become useful for e.g. build attestations directly from the invoked build backend. But that's a while off, so I'll make this repo a better example for the time being 🙂

**Comment by woodruffw** [comment]
Doing with #105.

**Comment by webknjaz** [comment]
> I also think the packaging guidance may need to become more nuanced over time: `id-token: write` may eventually become useful for e.g. build attestations directly from the invoked build backend.

Well, I still maintain that it's dangerous in the context of GitHub because of how it OIDC tokens can access more things than is obvious. So I'd keep recommending producing build signatures in a separate job.

**Comment by woodruffw** [comment]
What, what else can the OIDC credentials access? Or do you mean more generally in the sense that a workflow with `id-token: write` can control `aud` and issue credentials for any audience?

**Comment by woodruffw** [comment]
I split this up a bit more with #106: the build step now has zero permissions, and the sign and publish steps are now split as well 🙂
