### ISSUE TITLE
(Question) Categorizing a Py_XDECREF ABI violation report

### ISSUE THREAD

**Issue by nicholasjng** [trailofbits/abi3audit#83]
Thank you for making this package! I have a question:

I'm currently building a Bazel support project for [nanobind](https://github.com/wjakob/nanobind), a C++ project for generating lean, fast Python bindings of C++ code. It provides stable ABI support starting from Python 3.12, and supports generating as-small-as-possible bindings by setting the `-Os` optimization flag.

I've been implementing build flags and options to match its default CMake config as closely as possible, with (what I thought) the last step being defaulting size optimizations (read: supplying `-Os` to clang/gcc) to True.

I test on a small [example bindings project](https://github.com/wjakob/nanobind_example), and use `abi3audit` to check Python 3.12 wheels for stable ABI violations. Windows and MacOS are green, but Linux has since generated reports of the  `Py_XDECREF` symbol (which is a preprocessor macro apparently?) being contained in the wheel, which it flags as an ABI violation.

The C++ code I'm building into an extension is the easiest it can be:

```cpp
#include <nanobind/nanobind.h>

namespace nb = nanobind;

using namespace nb::literals;

NB_MODULE(nanobind_example_ext, m) {
    m.def("add", [](int a, int b) { return a + b; }, "a"_a, "b"_a);
}
```

i.e., it doesn't even import Python headers, so at most this is an internal nanobind thing. I'm not too familiar with its internals, but I was confused because it only happens reproducibly on Linux with `-Os` enabled. 

From what I've read in a quick Internet search, this seems to inhibit inlining on gcc, which might be relevant with some of these refcounting APIs being `static inline`. What is your opinion on this?

Related threads and links: 
- https://github.com/trailofbits/abi3audit/issues/82 (though that's about the leading-underscore `_Py_XDECREF` API)
- https://github.com/trailofbits/abi3audit/issues/55 (about inlined reference counting symbols)
- [My GitHub CI logs](https://github.com/nicholasjng/nanobind-bazel/actions/runs/8497459334/job/23276065475?pr=20).

**Comment by nicholasjng** [comment]
Additional info:

1. I'm building 3.12 wheels with `py_limited_api = True` in setuptools and `-DPy_LIMITED_API=0x030C0000`.
2. The Linux wheel audit is green when building without `-Os`.

**Comment by nicholasjng** [comment]
Thanks for the great write-up! I'm going to raise this in the nanobind repo, but it appears that abi3audit works perfectly as intended here.

**Comment by woodruffw** [comment]
No problem! Thank you for the detailed report, and for using `abi3audit`!
