### ISSUE TITLE
[Feature request] Support globs on Windows

### ISSUE THREAD

**Issue by davidelahoz** [trailofbits/abi3audit#92]
In order to use abi3audit automatically after a wheel has been build, it would be nice to be able to pass a directory instead of the wheel name as sometimes more than a single wheel is generated and the wheel name changes according to the module version

**Comment by woodruffw** [comment]
Thanks for filing this issue, @davidelahoz!

> In order to use abi3audit automatically after a wheel has been build, it would be nice to be able to pass a directory instead of the wheel name as sometimes more than a single wheel is generated and the wheel name changes according to the module version

Is there a reason you can't use `abi3audit some-dir/*.whl`? This (multiple input files) should already work, and doesn't require `abi3audit` to handle a special directory case.

(This is similar to how `twine` and other distribution-handling tools work: they don't take a directory, they take one or more files.)

**Comment by davidelahoz** [comment]
That actually would work. I couldn't find how to achieve that

**Comment by davidelahoz** [comment]
> Thanks for filing this issue, @davidelahoz!
> 
> > In order to use abi3audit automatically after a wheel has been build, it would be nice to be able to pass a directory instead of the wheel name as sometimes more than a single wheel is generated and the wheel name changes according to the module version
> 
> Is there a reason you can't use `abi3audit some-dir/*.whl`? This (multiple input files) should already work, and doesn't require `abi3audit` to handle a special directory case.
> 
> (This is similar to how `twine` and other distribution-handling tools work: they don't take a directory, they take one or more files.)

I'm trying to use `abi3audit ./dist/*.whl`, but it is unable to find the wheels. Using `./dist/wheelname.whl` works fine. It seems that using *.whl is not supported by abi3audit

**Comment by woodruffw** [comment]
> I'm trying to use `abi3audit ./dist/*.whl`, but it is unable to find the wheels. Using `./dist/wheelname.whl` works fine. It seems that using *.whl is not supported by abi3audit


Can you share the exact error you're getting, as well as the platform you're on? `*.whl` is a feature of your shell, not `abi3audit`. If your shell doesn't support globbing, then there's nothing `abi3audit` can do (I have no plan to add explicit glob support, since AFAIK it's only Windows' CMD that behaves this way.)

**Comment by davidelahoz** [comment]
> > I'm trying to use `abi3audit ./dist/*.whl`, but it is unable to find the wheels. Using `./dist/wheelname.whl` works fine. It seems that using *.whl is not supported by abi3audit
> 
> 
> Can you share the exact error you're getting, as well as the platform you're on? `*.whl` is a feature of your shell, not `abi3audit`. If your shell doesn't support globbing, then there's nothing `abi3audit` can do (I have no plan to add explicit glob support, since AFAIK it's only Windows' CMD that behaves this way.)
> 

I don't have access to my computer right now, but it shows an error saying that no files called *.whl could be found. I'm on windows

**Comment by davidelahoz** [comment]
Thanks!

**Comment by woodruffw** [comment]
@davidelahoz could you give the changes in #93 a try? I think that should address the glob issue you're seeing on Windows.

**Comment by davidelahoz** [comment]
Of course, I'll try it tomorrow (I don't have access to my computer right now)

**Comment by davidelahoz** [comment]
> @davidelahoz could you give the changes in #93 a try? I think that should address the glob issue you're seeing on Windows.

I've just tested it. It works fine on windows

**Comment by woodruffw** [comment]
Much appreciated!

**Comment by woodruffw** [comment]
Cut with v0.0.11.
