### ISSUE TITLE
ELF: Handle `STB_GNU_UNIQUE`

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/abi3audit#98]
From https://github.com/trailofbits/abi3audit/issues/94: some versions of the GNU toolchain will emit `STB_GNU_UNIQUE` visibilities in C++ binaries that use templated static locals. We should handle these as local visibility symbols.

This needs to be done gingerly: we need to make sure the ELF binary is built with the GNU toolchain before assuming that `STB_LOOS == STB_GNU_UNIQUE` in terms of semantics.

**Comment by wsfulton** [comment]
Thanks, confirmed that this fixes the issue I reported at the end of #94.
